### PR TITLE
PETSc stages

### PR DESCRIPTION
**Pull request by IskanderI**
Added 4 stages:

1. Thermal solver 
2. SNES Solve
3. Advect markers
4. Saving output

I am not sure about Thermal solver since it usually solves very fast.
We should maybe discuss what is the best place to put stages.

Here is a short snippet on run with -log_view now.
image

### CODE REVIEW

**Comment by boriskaus** [comment]
Thanks a lot, this is great!

Does the thermal solver also take this little time in the Diffusion solver benchmark?

**Comment by IskanderI** [comment]
> Thanks a lot, this is great!
> 
> Does the thermal solver also take this little time in the Diffusion solver benchmark?
No it does not show up there.
I put profiler for thermal diffusion in timestep look already. 
I put it at 
ierr = JacResInitTemp(&lm->jr); CHKERRQ(ierr);

But to measure thermal diffuion in Diffusion solver benchmark I will need to put it in Initial guess part of the code.
Probably this function.
ierr = LaMEMLibDiffuseTemp(lm); CHKERRQ(ierr);

**Comment by boriskaus** [comment]
Also note that the adjoint tests fail with this:
```
[0]PETSC ERROR: Duplicate stage name given: Thermal solver
```
this requires fixing.

**Comment by boriskaus** [comment]
ok, now this works and I'm in principle happy to merge it. For consistency it would be good if you can increment the version of LaMEM such that we release a new version (easier when doing benchmarking later).
Can you please add that (also in the documentation)?

**Comment by boriskaus** [comment]
Thanks - you also need to change it in the `LaMEM.h` file (I believe) as the version number of LaMEM is printed at the beginning of the simulation.

**Pull request merged**
